[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=src"
testpaths = ["tests"]
norecursedirs = ".venv trash archive images .pytest_cache"