export const NODE_MIN_WIDTH = 150;
export const NODE_PADDING_VERTICAL = 10;
export const NODE_PADDING_HORIZONTAL = 15;
export const NODE_BORDER_WIDTH = 2;
export const NODE_BORDER_RADIUS = 8;

export const INDICATOR_EDGE_OFFSET = 8;

export const COOKING_STATE_DIAMETER = 12;
export const COOKING_STATE_LEFT = INDICATOR_EDGE_OFFSET;
export const COOKING_STATE_TOP = INDICATOR_EDGE_OFFSET;

export const ERROR_WARNING_DIAMETER = 12;
export const ERROR_WARNING_LEFT = INDICATOR_EDGE_OFFSET;
export const ERROR_WARNING_BOTTOM = INDICATOR_EDGE_OFFSET;
export const ERROR_WARNING_DUAL_WIDTH = 6;
export const ERROR_WARNING_DUAL_GAP = 2;

export const TEMPLATE_CIRCLE_DIAMETER = 12;
export const TEMPLATE_CIRCLE_RIGHT = INDICATOR_EDGE_OFFSET;
export const TEMPLATE_CIRCLE_FONT_SIZE = 14;

export const TEXT_SPACING_FROM_INDICATOR = 8;
export const TEXT_AREA_TOP = INDICATOR_EDGE_OFFSET;
export const TEXT_AREA_BOTTOM = INDICATOR_EDGE_OFFSET;
export const TEXT_AREA_LEFT = ERROR_WARNING_LEFT + ERROR_WARNING_DIAMETER + TEXT_SPACING_FROM_INDICATOR;
export const TEXT_AREA_RIGHT = TEMPLATE_CIRCLE_RIGHT + TEMPLATE_CIRCLE_DIAMETER + TEXT_SPACING_FROM_INDICATOR;

export const TEXT_LINE_HEIGHT = 20;
export const TEXT_FONT_SIZE = 14;
export const TEXT_TYPE_FONT_SIZE = 9;
export const TEXT_GLYPH_SIZE = 14;
export const TEXT_ELEMENT_MARGIN = 2;
export const TEXT_CONTENT_GAP = 6;
export const TEXT_HEADER_GAP = 8;

export const HANDLE_DIAMETER = 10;
export const HANDLE_BORDER_WIDTH = 2;
export const HANDLE_OFFSET = 6;

export const COLOR_COOKING_UNCOOKED = '#ff9800';
export const COLOR_COOKING_UNCHANGED = '#4caf50';
export const COLOR_COOKING_COOKING = '#2196f3';

export const COLOR_ERROR = '#A855F7';
export const COLOR_ERROR_OUTLINE = '#D4AAFB';
export const COLOR_WARNING = '#FCD34D';
export const COLOR_WARNING_OUTLINE = '#FEE9A6';

export const COLOR_BYPASS_DEFAULT = '#CED0D5';
export const COLOR_BYPASS_HOVER = '#E5E7EB';

export const COLOR_TEXT_ACTIVE = '#1F2937';
export const COLOR_TEXT_BYPASSED = '#4B5563';

export const COLOR_BG_ACTIVE = 'white';
export const COLOR_BG_BYPASSED = '#374151';
export const COLOR_BORDER_ACTIVE = '#ccc';
export const COLOR_BORDER_BYPASSED = '#4B5563';
export const COLOR_BORDER_SELECTED = '#1976d2';

export const COLOR_HANDLE_INPUT_BORDER = '#E5E7EB';
export const COLOR_HANDLE_INPUT_FILL = '#FFFFFF';
export const COLOR_HANDLE_OUTPUT_BORDER = '#10B981';
export const COLOR_HANDLE_OUTPUT_FILL = '#D1FAE5';
export const COLOR_HANDLE_BYPASSED_BORDER = '#6B7280';
export const COLOR_HANDLE_BYPASSED_FILL = '#9CA3AF';

export const OPACITY_BYPASSED = 0.6;
export const OPACITY_ACTIVE = 1;
