name: Docker Image CI

on:
  push:
    branches: [ "mainXXX" ]
  pull_request:
    branches: [ "mainXXX" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag my-image-name:$(date +%s)
